=== hackatonIVCIMSC/Ethereum_Ricardian_Token/old_html/voucherSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema elementFormDefault="qualified" targetNamespace="urn:ietf:params:xml:ns:vts-lang"
	xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gvl="urn:ietf:params:xml:ns:vts-lang">
	<element name="Voucher" type="gvl:VoucherType" />
	<complexType name="VoucherType">
		<sequence>
			<element ref="gvl:Title" />
			<element maxOccurs="1" minOccurs="1" ref="gvl:Issuer" />
			<element maxOccurs="unbounded" minOccurs="1" ref="gvl:Provider" />
			<element maxOccurs="unbounded" minOccurs="1" ref="gvl:Merchandise" />
			<element maxOccurs="unbounded" minOccurs="1" ref="gvl:Description" />
			<element maxOccurs="unbounded" minOccurs="1" ref="gvl:Condition" />
			<element maxOccurs="1" minOccurs="1" ref="gvl:Value" />
			<element maxOccurs="1" minOccurs="1" ref="gvl:ValidPeriod" />
		</sequence>
	</complexType>
	<element name="Title" type="string" />
	<element name="Issuer" type="gvl:RoleType" />
	<element name="Provider" type="gvl:RoleType" /> 
	<element name="Merchandise" type="string" />
	<element name="Description" type="string" />
	<element name="Condition" type="string" />
	<element name="ValidPeriod" type="gvl:ValidPeriodType" />
	<complexType mixed="true" name="RoleType">
		<sequence>
			<element name="name" type="string" />
			<element name="account" type="string" />
			<element name="shortname" type="string" />
			<element name="longname" type="string" />
			<element name="postaddress" type="string" />
			<element name="country" type="string" />
			<element name="registration" type="string" />
			<element name="Bzz" type="string" />
			<element name="account" type="string" />
		</sequence>
	</complexType>
	<element name="Value" type="gvl:ValueType" />
	<complexType name="ValueType">
		<sequence minOccurs="1">
			<element name="Fixed" type="gvl:FixedValueType" />
		</sequence>
	</complexType>
	<complexType name="RatioValueType">
		<attribute name="percentage" use="required">
			<simpleType>
				<restriction base="float">
					<maxInclusive value="100" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	<complexType name="FixedValueType">
	<sequence>
		<element maxOccurs="1" minOccurs="1"  name="currency" type="string" />
        <element maxOccurs="1" minOccurs="1"  name="voucherTokenSymbol" type="string" />
        <element maxOccurs="1" minOccurs="1"  name="voucherTokenLogoBzz"  type="string" />
        <element maxOccurs="1" minOccurs="1"  name="amount" type="float" />
		<element maxOccurs="1" minOccurs="1"  default="0" name="decimalPower" type="short" />
	</sequence>
	</complexType>
	<complexType name="ValidPeriodType">
		<attribute name="start" type="dateTime" />
		<attribute name="end" type="dateTime" />
	</complexType>
</schema>

=== hackatonIVCIMSC/Ethereum_Ricardian_Token/cooperativeVoucher.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="voucher.xsl"?>
<gvl:Voucher xmlns:gvl="urn:ietf:params:xml:ns:vts-lang"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="urn:ietf:params:xml:ns:vts-lang voucherSchema.xsd ">
<gvl:Title>Title</gvl:Title>
<gvl:Issuer>
<gvl:name>KOMPU A.C.M.S.</gvl:name>
<gvl:account>account</gvl:account>
<gvl:shortname>KOMPU</gvl:shortname>
<gvl:longname>Kompu Agricultural co-operative Marketing Society</gvl:longname>
<gvl:postaddress>NAFED HOUSE, Siddhartha Enclave, Ashram Chowk, New Delhi 110 014, India</gvl:postaddress>
<gvl:country>India</gvl:country>
<gvl:registration>91-11-26341807</gvl:registration>
<gvl:Bzz>Bzz</gvl:Bzz>
</gvl:Issuer>
<gvl:Provider>
<gvl:name>name</gvl:name>
<gvl:account>account</gvl:account>
<gvl:shortname>shortname</gvl:shortname>
<gvl:longname>longname</gvl:longname>
<gvl:postaddress>postaddress</gvl:postaddress>
<gvl:country>country</gvl:country>
<gvl:registration>registration</gvl:registration>
<gvl:Bzz>Bzz</gvl:Bzz>
<gvl:account>account</gvl:account>
</gvl:Provider>
<gvl:Value>
<gvl:Fixed>
<gvl:currency>kgEqC</gvl:currency>
<gvl:voucherTokenSymbol>Џ</gvl:voucherTokenSymbol>
<gvl:voucherTokenLogoBzz>voucherTokenLogoBzz</gvl:voucherTokenLogoBzz>
<gvl:amount>100000000</gvl:amount>
<gvl:decimalPower>2</gvl:decimalPower>
</gvl:Fixed>
</gvl:Value>
<gvl:Merchandise>Crops, as any plant, macroscopic fungus, or alga cultivated in agriculture or aquaculture (algaculture). </gvl:Merchandise>
<gvl:Merchandise>Rice, paddy</gvl:Merchandise>
<gvl:Merchandise>Cow's milk, whole, fresh</gvl:Merchandise>
<gvl:Merchandise>Cattle, meat</gvl:Merchandise>
<gvl:Merchandise>Pig, meat</gvl:Merchandise>
<gvl:Merchandise>Chicken, meat</gvl:Merchandise>
<gvl:Merchandise>Wheat</gvl:Merchandise>
<gvl:Merchandise>Soybeans</gvl:Merchandise>
<gvl:Merchandise>Tomatoes</gvl:Merchandise>
<gvl:Merchandise>Sugar cane</gvl:Merchandise>
<gvl:Merchandise>Maize (Corn)</gvl:Merchandise>
<gvl:Merchandise>Eggs, in shell</gvl:Merchandise>
<gvl:Merchandise>Potatoes</gvl:Merchandise>
<gvl:Merchandise>Vegetables, not elsewhere specified</gvl:Merchandise>
<gvl:Merchandise>Grapes</gvl:Merchandise>
<gvl:Merchandise>Water Buffalo milk</gvl:Merchandise>
<gvl:Merchandise>Cotton, lint</gvl:Merchandise>
<gvl:Merchandise>Apples</gvl:Merchandise>
<gvl:Merchandise>Bananas</gvl:Merchandise>
<gvl:Merchandise>Cassava (yuca)</gvl:Merchandise>
<gvl:Merchandise>Mangos, Mangosteens, Guavas</gvl:Merchandise>
<gvl:Merchandise>Sheep, meat</gvl:Merchandise>
<gvl:Merchandise>Coffee</gvl:Merchandise>
<gvl:Merchandise>Palm oil</gvl:Merchandise>
<gvl:Merchandise>Onions, dry</gvl:Merchandise>
<gvl:Merchandise>Beans, dry and green</gvl:Merchandise>
<gvl:Merchandise>Peanuts, in shell</gvl:Merchandise>
<gvl:Merchandise>Olives</gvl:Merchandise>
<gvl:Merchandise>Rapeseed</gvl:Merchandise>
<gvl:Merchandise>Chilis and peppers, green and dry</gvl:Merchandise>
<gvl:Merchandise>Rubber</gvl:Merchandise>
<gvl:Merchandise>Tea</gvl:Merchandise>
<gvl:Merchandise>Oranges</gvl:Merchandise>
<gvl:Merchandise>Cucumbers</gvl:Merchandise>
<gvl:Merchandise>Yams</gvl:Merchandise>
<gvl:Merchandise>Peaches, nectarines</gvl:Merchandise>
<gvl:Merchandise>Lettuce, Chicory</gvl:Merchandise>
<gvl:Merchandise>Cacao (Chocolate)</gvl:Merchandise>
<gvl:Merchandise>Goat, meat</gvl:Merchandise>
<gvl:Merchandise>Sunflower seed</gvl:Merchandise>
<gvl:Merchandise>Sugar beets</gvl:Merchandise>
<gvl:Merchandise>Watermelons</gvl:Merchandise>
<gvl:Merchandise>Buffalo, meat</gvl:Merchandise>
<gvl:Merchandise>Asparagus</gvl:Merchandise>
<gvl:Merchandise>Turkey, meat</gvl:Merchandise>
<gvl:Merchandise>Carrots, Turnips</gvl:Merchandise>
<gvl:Merchandise>Duck, meat</gvl:Merchandise>
<gvl:Merchandise>Coconuts</gvl:Merchandise>
<gvl:Merchandise>Tangerines</gvl:Merchandise>
<gvl:Merchandise>Almonds</gvl:Merchandise>
<gvl:Merchandise>Lemons, Limes</gvl:Merchandise>
<gvl:Merchandise>Strawberries</gvl:Merchandise>
<gvl:Merchandise>Walnuts</gvl:Merchandise>
<gvl:Desciption>“Processing Year” is the twelve-month period commencing January 1 and ending on December 31 of each year, unless otherwise changed by the Cooperative.</gvl:Description>
<gvl:Desciption></gvl:Description>
<gvl:Desciption>“Committed Bushels” is the number of bushels of [commodity] that Member has committed to deliver annually to the Cooperative hereunder.</gvl:Description>
<gvl:Desciption>“Delivery Period” is the delivery period established for a Processing Year as determined by the Board in its discretion.</gvl:Description>
<gvl:Desciption>“Input Commodity Payment” is the per unit price of the delivered [commodity] established by the Board of Directors, in its discretion, prior to the beginning of each Delivery Period.</gvl:Description>
<gvl:Description>Each community, a producer of agricultural products, hereinafter referred to as “Community,” together with other signers of agreements similar hereto, have a cooperative association under the laws of the Country of the Association</gvl:Description>
<gvl:Description>(a) The association shall be organized with suitable articles of incorporation and bylaws as determined by an organizational committee.</gvl:Description>
<gvl:Description>(b) This committee may, by vote of a majority of its members, increase its membership, fill any vacancy therein, and appoint any subcommittees deemed necessary to conduct its affairs. The committee, or any subcommittee designated by it, may prescribe an organization fee to be paid by each person signing an organization agreement and may incur necessary obligations, make necessary expenditures,
and take any such action as may, in its discretion, be deemed advisable to further the organization of the association.</gvl:Description>
<gvl:Description>A kgEqC is the price of a kilo of Rice, and stands for a kg "Equivalent" in Crops. Each crop will have a price for a kilo a a multimplier of kgEqC</gvl:Description>
<gvl:Condition>Each community agrees to sign a marketing agreement committing all (product) produced by Producer, on land owned or leased by Producer, to the cooperative for direct marketing, processing, or other disposition as the cooperative sees fit.</gvl:Condition>
<gvl:Condition>Each community estimates such production in a quentity expressed as its "promise"</gvl:Condition>
<gvl:Condition>Each community agrees to sign a marketing agreement to commit (promise units) of (product), produced by the Community, to the cooperative for direct marketing, processing, or other disposition as the cooperative sees fit.</gvl:Condition>
<gvl:ValidPeriod end="2017-12-31T12:00:00" start="2020-12-31T12:00:00" />
</gvl:Voucher>

=== hackatonIVCIMSC/Ethereum_Ricardian_Token/voucher.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="voucher.xsl"?>
<gvl:Voucher xmlns:gvl="urn:ietf:params:xml:ns:vts-lang"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:ietf:params:xml:ns:vts-lang voucherSchema.xsd ">
	<gvl:Title>Title</gvl:Title>
	<gvl:Issuer>
		<gvl:name>name</gvl:name>
		<gvl:account>account</gvl:account>
		<gvl:shortname>shortname</gvl:shortname>
		<gvl:longname>longname</gvl:longname>
		<gvl:postaddress>postaddress</gvl:postaddress>
		<gvl:country>country</gvl:country>
		<gvl:registration>registration</gvl:registration>
		<gvl:Bzz>Bzz</gvl:Bzz>
		<gvl:account>account</gvl:account>
	</gvl:Issuer>
	<gvl:Provider>
		<gvl:name>name</gvl:name>
		<gvl:account>account</gvl:account>
		<gvl:shortname>shortname</gvl:shortname>
		<gvl:longname>longname</gvl:longname>
		<gvl:postaddress>postaddress</gvl:postaddress>
		<gvl:country>country</gvl:country>
		<gvl:registration>registration</gvl:registration>
		<gvl:Bzz>Bzz</gvl:Bzz>
		<gvl:account>account</gvl:account>
	</gvl:Provider>
	<gvl:Value>
		<gvl:Fixed>
			<gvl:currency>voucherTokenName</gvl:currency>
			<gvl:voucherTokenSymbol>voucherTokenSymbol</gvl:voucherTokenSymbol>
			<gvl:voucherTokenLogoBzz>voucherTokenLogoBzz</gvl:voucherTokenLogoBzz>
			<gvl:amount>1000000</gvl:amount>
			<gvl:decimalPower>2</gvl:decimalPower>
		</gvl:Fixed>
	</gvl:Value>
	<gvl:Merchandise>Lorem ipsum dolor sit amet, autem mucius ea quo, et exerci soluta placerat mea, qui habeo molestie ad. Vim eripuit fabulas copiosae at, error convenire et ius. Te nostrud fierent nam, ea autem iusto denique duo. Eu mel modus dictas placerat, tollit dicunt intellegam ei eum, no eum nibh dicat. Id imperdiet posidonium interpretaris pro, has te wisi graeco. Exerci appareat vel no, duo ex corpora legendos patrioque. Nec an veri natum putant.</gvl:Merchandise>
	<gvl:Merchandise>Ea debet nonumy vim, ex labore euripidis persequeris eum, hinc sensibus ea sit. Vix id dolore diceret mnesarchum, has lucilius consulatu ex. Erat justo vix ne, nam molestie mnesarchum ut, quem mandamus at mea. Eos quis delectus scaevola ad, per bonorum quaestio ne. Nec velit volutpat ea. No sea evertitur torquatos reformidans, est minimum neglegentur an.</gvl:Merchandise>
	<gvl:Merchandise>Tacimates deseruisse has ex. Adhuc scripta persius eos cu, sea eu sale meliore. Usu cu falli assueverit, meis inimicus ea eum. Ius perfecto adipiscing te, porro conceptam ad nam. Ridens utroque percipitur mei ex, ad minim tibique accusata quo. Mea id stet equidem. Vix ad tantas primis rationibus, te possit ornatus gloriatur mea.</gvl:Merchandise>
	<gvl:Merchandise>Aeque graeco nusquam ei mea, ius tractatos imperdiet iracundia id. Nusquam adversarium ea has, cum in audiam convenire. Vim probo eirmod ex. Ei quo amet appetere. Scripta noluisse ex est, eu enim commodo dissentiunt mei.</gvl:Merchandise>
	<gvl:Description>Ne nec vivendum conclusionemque, sed at clita dolores oporteat, at sed erat virtute. Vocent scaevola et duo, facilisi euripidis accommodare mei in. Cu qui delenit constituam contentiones, cum an saperet eleifend oportere, cu invidunt volutpat eam. Duo unum mazim ex, sea minimum pertinax voluptaria cu, nam et case detracto.</gvl:Description>
	<gvl:Description>Possit appetere persequeris id eos, eos an nisl tota efficiantur. At mei munere partem legendos, ad sea oratio noster iudicabit, ea liber eligendi consequat eos. Ea sed nonumes erroribus voluptatibus, et pri ferri electram. Ut sed bonorum sanctus, duo dicat quaestio concludaturque at. Et vis soleat primis, elit ullum liber eos in.</gvl:Description>
	<gvl:Description>Cu purto diceret interpretaris vis, sed ne placerat qualisque, minimum quaerendum referrentur in vim. Integre feugiat te vim, ex animal docendi dignissim pro, timeam dissentiunt usu et. Brute interpretaris in sit, at vix habeo fabulas referrentur, eu idque graeco cotidieque duo. Sanctus torquatos cum id, ea oratio recusabo voluptatibus his.</gvl:Description>
	<gvl:Condition>Nam elit fastidii vivendum eu, aliquip voluptua principes cum ex, aliquip volumus nominavi per cu. Ut pertinax delicata adversarium mel. Solet tantas partiendo quo ad, ne vix tritani expetenda. Purto percipit vel cu, tamquam voluptatibus his ut. Per ei ullum probatus constituto, ne noluisse verterem mea.</gvl:Condition>
	<gvl:Condition>Ex viris iisque sit. Ad eirmod mediocrem intellegam has, ad tempor corrumpit conceptam duo, menandri abhorreant no vis. Sit enim possim suscipiantur eu, ea qui facilisis moderatius. No sea offendit platonem interpretaris, zril electram imperdiet vis ut. Aliquip noluisse ex cum, at nam solet ubique delectus.</gvl:Condition>
	<gvl:Condition>Et natum munere nemore sed. Iriure copiosae ea nec, has doming torquatos at, no vidit dissentiunt vituperatoribus est. Cum aeterno debitis voluptatum ut, in amet adipiscing quaerendum eum. Detracto ponderum pri no, propriae iudicabit id has, cibo suavitate et has. Id pri nusquam maluisset, ex oportere ullamcorper interpretaris sed, legere sensibus definitiones eu eos. Sed tota accumsan suscipit ea, illud electram ad usu.</gvl:Condition>
	<gvl:ValidPeriod end="2001-12-31T12:00:00" start="2001-12-31T12:00:00" />
</gvl:Voucher>
